name: POC - Trivy (fs + config + secrets + image + SBOM)

on: 
  pull_request:
  push:
    branches: [ main ]
  workflow_dispatch:
  # schedule:
  #   - cron: '15 2 * * 0' #run at 02:15, only on Sunday

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  repo_scan:
    name: Repo scan (vuln + secrets + config)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Trivy FS + Config scan (SARIF)
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: fs
          scan-ref: .
          scanners: vuln,secret,config
          format: sarif
          output: trivy-fs.sarif
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          version: v0.70.0
          #exit-code: 1           # <--- This fails the step if HIGH/CRITICAL vulns found

      - name: Upload repo scan artifact
        uses: actions/upload-artifact@v7
        #if: ${{ always() }}         # <--- This runs regardless of prior step failures
        with:
          name: trivy-fs
          path: trivy-fs.sarif

      - name: Upload SARIF to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: trivy-fs.sarif

  sbom:
    name: Generate SBOM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Generate SBOM (CycloneDX)
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: fs
          scan-ref: .
          format: cyclonedx
          output: sbom.cdx.json
          version: v0.70.0

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v7
        with:
          name: sbom-cyclonedx
          path: sbom.cdx.json

  image_scan:
    name: Build + scan Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Build Docker image
        run: docker build --build-arg CI=true -t lca-collaboration:poc .

      - name: Trivy image scan (SARIF)
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: lca-collaboration:poc
          format: sarif
          output: trivy-image.sarif
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          version: v0.70.0
          #exit-code: 1

      - name: Upload image scan artifact
        uses: actions/upload-artifact@v7
        #if: ${{ always() }}         # <--- This runs regardless of prior step failures
        with:
          name: trivy-image
          path: trivy-image.sarif
          
      - name: Upload SARIF to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: trivy-image.sarif
